### ISSUE TITLE
RuntimeError when trainning on multiple GPUs.

### ISSUE THREAD

**Issue by zicha4555** [AlvinYH/Faster-VoxelPose#24]
Thanks for your work! when I run "python run/train.py --cfg configs/panoptic/jln64.yaml" with a " GPUS: '0,1' " setting in jln64.yaml, I got a RuntimeError as follows:

Exception has occurred: RuntimeError
Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/voxelpose.py", line 38, in forward
    bbox_preds = self.pose_net(input_heatmaps, meta, cameras, resize_transform)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/human_detection_net.py", line 81, in forward
    feature_cubes = self.project_layer(heatmaps, meta, cameras, resize_transform)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/project_whole.py", line 80, in forward
    sample_grids[c] = self.project_grid(cameras[curr_seq][c], w, h, nbins, resize_transform, device).squeeze(0)
  File "run/../lib/models/project_whole.py", line 52, in project_grid
    xy = do_transform(xy, resize_transform)
  File "run/../lib/utils/transforms.py", line 62, in affine_transform_pts_cuda
    out = torch.mm(t, torch.t(pts_homo))
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:277
  File "/newerDisk/zzh/python-projects/Faster-VoxelPose/lib/core/function.py", line 42, in train_3d
    cameras=cameras, resize_transform=resize_transform)
  File "/newerDisk/zzh/python-projects/Faster-VoxelPose/run/train.py", line 140, in main
    train_3d(config, model, optimizer, train_loader, epoch, final_output_dir, writer_dict)
  File "/newerDisk/zzh/python-projects/Faster-VoxelPose/run/train.py", line 170, in <module>
    main()
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/voxelpose.py", line 38, in forward
    bbox_preds = self.pose_net(input_heatmaps, meta, cameras, resize_transform)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/human_detection_net.py", line 81, in forward
    feature_cubes = self.project_layer(heatmaps, meta, cameras, resize_transform)
  File "/newerDisk/zzh/anaconda3/envs/fvpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "run/../lib/models/project_whole.py", line 80, in forward
    sample_grids[c] = self.project_grid(cameras[curr_seq][c], w, h, nbins, resize_transform, device).squeeze(0)
  File "run/../lib/models/project_whole.py", line 52, in project_grid
    xy = do_transform(xy, resize_transform)
  File "run/../lib/utils/transforms.py", line 62, in affine_transform_pts_cuda
    out = torch.mm(t, torch.t(pts_homo))
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:277

The GPUs used are two **RTX 1080ti**. The OS is **Ubuntu 16.04.7 LTS**. The CUDA version is 10.2 and pytorch version is 1.4.0. 
There would be no problem if running on single GPU, but the above error will happen in the case of multiple GPUs.

**Comment by AlvinYH** [comment]
Thanks for your interest in our work. Unfortunately, our code only supports single-GPU training right now :(
