### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by hyeon1263** [AlvinYH/Faster-VoxelPose#30]
### I use CUDA version: 11.4 & torch version: 1.11.0.
When I train the model on Panoptic dataset, this error occured.

```
Traceback (most recent call last):
  File "/home/vis/projects/Faster-VoxelPose/run/train.py", line 168, in <module>
    main()
  File "/home/vis/projects/Faster-VoxelPose/run/train.py", line 138, in main
    train_3d(config, model, optimizer, train_loader, epoch, final_output_dir, writer_dict)
  File "/home/vis/projects/Faster-VoxelPose/run/../lib/core/function.py", line 66, in train_3d
    accu_loss.backward()
  File "/home/vis/anaconda3/envs/pose/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/vis/anaconda3/envs/pose/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: 
[torch.cuda.FloatTensor [1, 32, 1]] is at version 8; expected version 6 instead. Hint: the backtrace further above shows the operation 
that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!"
```

I think the problem is the code below: 
```
if loss_joint > 0:
            optimizer.zero_grad()
            loss_joint.backward()
            optimizer.step()

        if accu_loss > 0 and (i + 1) % accumulation_steps == 0:
            optimizer.zero_grad()
            accu_loss.backward()
            optimizer.step()
            accu_loss = 0.0
        else:
            accu_loss += (loss_2d + loss_1d + loss_bbox) / accumulation_steps
```
There are two loss which apply backward().
If I use only one loss, then it works well. But using both make error like that.
Has anyone solved this problem?

**Comment by gpastal24** [comment]
https://github.com/AlvinYH/Faster-VoxelPose/issues/17#issuecomment-1420345510

Torch 1.4.0 had a bug that bypassed that error you are getting, and would compute the gradient regardless

**Comment by hyeon1263** [comment]
Is there other way to solve this without using torch 1.4.0?
